# Mandatory Configuration
title : Rohan Rajguru
url : https://srjoeraj.github.io/site/
note_template : template/note_template.html   # Template of note page
home_template : template/home_template.html   # Template of home page
feed_template : template/feed_template.xml   # Template of feed/rss page
home_path : public  # After built, static files will be generated here
content_path : content # All post notes markdown location
resource_path : static # All css, js, image location
home_md : content/home.md # Homepage content
header_md : content/header.md # Header content
footer_md : content/footer.md # Footer content

# Optional Configuration, Add your own configs here
site-title : Rohan's Website
css : Narangi.css
desc : Write anything that human and machine can understand.
mail : some@mail.com
            
